import { app, BrowserWindow, ipcMain } from 'electron';
import { createServer } from "http";
import { Server } from "socket.io"
import { startLANDiscovery } from './lan_discovery';
import { randomUUID } from "crypto";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const INSTANCE_ID = randomUUID(); // Each app instance has a unique ID
const PORT = 5001;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}


ipcMain.handle("get-instance-id", () => INSTANCE_ID);

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.removeMenu();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.webContents.once("did-finish-load", () => {
    mainWindow.webContents.send("set-instance-id", INSTANCE_ID);
  });

  const httpServer = createServer();
  const io = new Server(httpServer, {
    cors: { origin: "*"}
  })

  io.on("connection", (socket) => {
    console.log("New Socket.IO connection:", socket.id);

    socket.on("chat-message", (msg) => {
      console.log("Message received:", msg);
      // Broadcast to all others
      socket.broadcast.emit("chat-message", msg);
      // Send to Renderer
      mainWindow.webContents.send("chat-message", msg);
    })
  })

  httpServer.listen(PORT, () => {
    console.log(`Socket.IO server listening on port ${PORT}`)
  })

  ipcMain.on("send-chat", (_, msg) => {
    io.emit("chat-message", msg);
  })

  startLANDiscovery(mainWindow, PORT);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.